In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [49]:
data = pd.read_csv("50_Startups.csv")

In [51]:
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [53]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [55]:
# Using oneHot Encoding because it's a nominal data> converting categorical data to numerical data

df = pd.get_dummies(data,drop_first=True, dtype=int)

In [57]:
df.head(5)

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   
3  144372.41       118671.85        383199.62  182901.99              0   
4  142107.34        91391.77        366168.42  166187.94              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [59]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [61]:
independent = df[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [65]:
independent.head(5)

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10              0               1
1  162597.70       151377.59        443898.53              0               0
2  153441.51       101145.55        407934.54              1               0
3  144372.41       118671.85        383199.62              0               1
4  142107.34        91391.77        366168.42              1               0

In [71]:
dependent = df[["Profit"]]


In [75]:
dependent.head(5)

Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [93]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=1)

In [95]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [97]:
#Weight finding
weight = regressor.coef_
weight

array([[ 7.70711613e-01, -1.41653527e-02,  3.50988115e-02,
        -9.56828109e+02, -3.06310628e+02]])

In [99]:
#Bias
bias = regressor.intercept_
bias

array([49472.15917655])

In [101]:
y_pred = regressor.predict(X_test)

In [103]:
from sklearn.metrics import r2_score
r2score = r2_score(y_test,y_pred)

In [105]:
r2score

0.952967609542534

In [109]:
# once model is finilized we need to dump/save the model for further use:
import pickle
filename = "finilized_mul_linear_reg.sav"
pickle.dump(regressor, open(filename,'wb'))

In [117]:
#For sample testing reloaded the saved model to pridect new vaariable or features by passing new values

loaded_model = pickle.load(open("finilized_mul_linear_reg.sav",'rb'))
result = loaded_model.predict([[91234,108623.10,24930.22,1,0]])

In [119]:
result

array([[118166.77090841]])